Improve caching creation and use

diff --git a/container_build/make-push b/container_build/make-push
--- a/container_build/make-push
+++ b/container_build/make-push
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 set -euo pipefail
-
 NAME=${NAME:-terrain-model}
 REPO=${REPO:-ghcr.io/cseelye}
 TAG=${TAG-latest}
+CACHE_REPO=${CACHE_REPO:-ghcr.io/cseelye}
 
 if [[ -n ${REPO} ]]; then
     IMAGE_NAME=${REPO}/${NAME}
@@ -11,14 +11,41 @@ else
     IMAGE_NAME=${NAME}
 fi
 
+if [[ -n ${CACHE_REPO} ]]; then
+    CACHE_IMAGE_NAME=${CACHE_REPO}/${NAME}
+elif [[ -n ${REPO} ]]; then
+    CACHE_IMAGE_NAME=${REPO}:${NAME}
+else
+    echo "CACHE_REPO and REPO cannot both be empty"
+    exit 1
+fi
 
-for stage in prod dev; do
+# This build process uses buildx remote layer caching, so docker must be logged into the registry being used with permissions to pull and push
+
+# Build cache-from args so each build can pull from every cache layer
+# Normally this is only useful when the cache is incomplete
+CACHE_FROM=""
+for target in $(ggrep -oP "FROM \S+ AS (\S+)" Dockerfile | awk '{print $4}' | tr '\n' ' ' | tac -s ' '); do
+    CACHE_FROM="${CACHE_FROM} \
+        --cache-from type=registry,ref=${CACHE_IMAGE_NAME}.${target}-buildcache"
+done
+
+for target in prod dev; do
 (
     fullname=${IMAGE_NAME}.${target}:${TAG}
     if [[ ${target} == "prod" ]]; then
         fullname=${IMAGE_NAME}:${TAG}
     fi
     set -x
-    docker image push ${fullname}
+    docker buildx build 
+        --pull \
+        --push \
+        --load \
+        ${CACHE_FROM} \
+        --cache-to type=registry,ref=${CACHE_IMAGE_NAME}.${target}-buildcache,mode=max \
+        --progress plain \
+        --target ${target} \
+        --tag ${fullname} \
+        .
 )
 done
